export const capabilityCatalog = [
  {
    id: "identity-access",
    group: "Plataforma",
    title: "Identidade, papeis e escopo",
    status: "delivered",
    summary: "Login por senha/Google, sessao, RBAC, tenancy e escopos por unidade e setor.",
    delivered: ["Matriz ADMIN, GESTOR, SAC, FINANCEIRO, SUPERVISOR e VENDEDOR", "Rotacao e invalidacao de sessao", "Testes negativos de permissao por API e navegador"],
    finalVision: "Identidade corporativa integrada ao provedor oficial, com ciclo de acesso e revisao periodica.",
    todos: ["Validar IdP e politicas no ambiente alvo", "Executar revisao humana de acessos antes do rollout"],
    intentionalReason: "Credenciais e IdP reais foram mantidos fora da demo para preservar isolamento e evitar exposicao.",
    href: "http://localhost:5173"
  },
  {
    id: "dashboard-search",
    group: "Operacao comercial",
    title: "Dashboard e busca operacional",
    status: "delivered",
    summary: "Central do dia com filas, indicadores, atalhos acionaveis e busca transversal.",
    delivered: ["Filas de notas, FAQ, ranking e notificacoes", "Filtros comerciais e navegacao contextual", "Estados de loading, vazio e erro cobertos"],
    finalVision: "Painel calibrado com indicadores e alertas do ambiente produtivo.",
    todos: ["Calibrar SLOs e alertas com volume real", "Validar leitura em monitores e zoom reais"],
    intentionalReason: "Metas operacionais reais dependem de baseline e aprovacao dos owners.",
    href: "http://localhost:5173"
  },
  {
    id: "danfe",
    group: "Operacao comercial",
    title: "DANFEs e revisao comercial",
    status: "delivered",
    summary: "Upload, extracao deterministica, diagnostico, revisao, auditoria e deduplicacao de notas.",
    delivered: ["XML e PDF textual no caminho deterministico", "Timeline e correcao manual auditavel", "Aprovacao alimenta ranking e extratos"],
    finalVision: "Ingestao resiliente em storage externo, filas e observabilidade production-like.",
    todos: ["Exercitar storage S3 e filas Redis no alvo", "Validar OCR apenas como fallback governado"],
    intentionalReason: "OCR e provedores live nao sao necessarios para o caminho principal da demo e ampliariam risco.",
    href: "http://localhost:5173"
  },
  {
    id: "ranking-campaigns",
    group: "Operacao comercial",
    title: "Ranking e campanhas",
    status: "delivered",
    summary: "Ranking explicavel por notas aprovadas, campanhas, snapshots e filtros de escopo.",
    delivered: ["Composicao por vendedor e grupo", "Explicacao por documento e ticket", "Snapshots e exportacao CSV"],
    finalVision: "Fechamentos e comparativos operando com agenda, volume e regras homologadas.",
    todos: ["Homologar regras comerciais finais", "Exercitar jobs e concorrencia no ambiente alvo"],
    intentionalReason: "Regras da demo sao sinteticas e nao afirmam politica comercial oficial.",
    href: "http://localhost:5173"
  },
  {
    id: "statements-reports",
    group: "Operacao comercial",
    title: "Extratos, relatorios e exports",
    status: "delivered",
    summary: "Consolidacao por vendedor e grupo, filtros reproduziveis e exportacoes com metadados.",
    delivered: ["Extratos lastreados por documentos aprovados", "CSV com contexto dos filtros", "Rotas de relatorio protegidas por papel"],
    finalVision: "Conciliacao homologada e distribuicao controlada no ambiente corporativo.",
    todos: ["Homologar formato com Financeiro", "Definir retencao e destino de exports reais"],
    intentionalReason: "Exports da demo ficam locais e usam apenas dados ficticios.",
    href: "http://localhost:5173"
  },
  {
    id: "professionals-licenses",
    group: "Operacao comercial",
    title: "Profissionais, vendedores e licencas",
    status: "partial",
    summary: "Cadastros operacionais, grupos, importacao controlada e verificacao de licencas.",
    delivered: ["Perfis e grupos comerciais", "Importacao com validacao", "Servicos e contratos testados"],
    finalVision: "Sincronizacao com fonte corporativa e ownership formal do cadastro.",
    todos: ["Definir sistema mestre", "Validar importacao com dataset autorizado"],
    intentionalReason: "A fonte corporativa e dados reais nao foram conectados nesta fase.",
    href: "http://localhost:5173"
  },
  {
    id: "wiki-faq",
    group: "Conhecimento",
    title: "Wiki e FAQ governadas",
    status: "delivered",
    summary: "Conhecimento pesquisavel com versoes, sugestoes, moderacao, historico e promocao de FAQ.",
    delivered: ["Editor Markdown seguro", "Aprovacao com comentario ao autor", "Tags, revisoes, anexos e presenca"],
    finalVision: "Base operacional revisada por owners, com ciclo de validade e indicadores de uso.",
    todos: ["Nomear curadores por dominio", "Revisar conteudo real antes de importar"],
    intentionalReason: "A demo usa conhecimento sintetico para nao transportar procedimentos sensiveis.",
    href: "http://localhost:5173"
  },
  {
    id: "announcements-notifications",
    group: "Conhecimento",
    title: "Avisos e notificacoes",
    status: "delivered",
    summary: "Comunicados internos, central de notificacoes, leitura e links contextuais.",
    delivered: ["Avisos segmentados", "Notificacoes deduplicadas", "Estados lido/nao lido e teclado"],
    finalVision: "Distribuicao integrada aos canais corporativos aprovados.",
    todos: ["Definir politica editorial", "Homologar canais externos sem duplicar mensagens"],
    intentionalReason: "Envio externo nao foi habilitado para evitar comunicacao acidental durante a demo.",
    href: "http://localhost:5173"
  },
  {
    id: "script-library",
    group: "Atendimento",
    title: "Scriptoteca",
    status: "delivered",
    summary: "Scripts versionados, busca, placeholders seguros, pacotes, sugestoes e copia auditada; o primeiro fluxo real aporta 17 mensagens rastreaveis.",
    delivered: ["17 mensagens do piloto SAUDE-DEV-TROCA-ESTORNO", "10 textos integrais validados e 7 rascunhos sinalizados", "Governanca, metricas e copia ligada a sessao"],
    finalVision: "Conteudo homologado por operacao e integrado ao fluxo guiado em todos os canais permitidos.",
    todos: ["Homologar os 7 textos sugeridos do piloto", "Adicionar os proximos fluxos reais com seus proprios scripts", "Medir efetividade com dados autorizados"],
    intentionalReason: "Copia explicita permanece o padrao; envio automatico foi proibido por seguranca.",
    href: "http://localhost:5173"
  },
  {
    id: "service-flows",
    group: "Atendimento",
    title: "Fluxos de Atendimento",
    status: "delivered",
    summary: "Construcao, versao, publicacao e execucao guiada; o primeiro fluxo real navega por escolhas auditadas sem se tornar modelo universal.",
    delivered: ["Piloto com 34 etapas, 9 encerramentos e 83 transicoes", "Decisoes clicaveis materializam somente o caminho escolhido", "17 scripts ligados as etapas e acoes irreversiveis humanas"],
    finalVision: "Biblioteca homologada cobrindo os procedimentos prioritarios da operacao.",
    todos: ["Fechar as 10 pendencias registradas do piloto", "Modelar os demais procedimentos como fluxos independentes", "Executar piloto controlado e medir abandono"],
    intentionalReason: "Este e deliberadamente o primeiro fluxo real; suas regras nao foram generalizadas para procedimentos futuros.",
    href: "http://localhost:5173"
  },
  {
    id: "caseflow-core",
    group: "CaseFlow",
    title: "CaseFlow Engine",
    status: "delivered",
    summary: "Casos, fatos, evidencias, conflitos, heuristica deterministica e planos compilados.",
    delivered: ["Persistencia tenant-scoped", "Resolucao especifica do piloto de saude apos suplemento", "Grafo v0.1 com firewall humano e mensagens da Scriptoteca"],
    finalVision: "Motor consultivo operando sobre fontes autorizadas e regras calibradas em shadow mode.",
    todos: ["Executar shadow mode live", "Homologar golden cases com operacao", "Fechar gate de recuperacao live"],
    intentionalReason: "A arquitetura esta pronta, mas fixtures locais nao autorizam decisao sobre casos reais.",
    href: "http://localhost:5173"
  },
  {
    id: "caseflow-guided-ui",
    group: "CaseFlow",
    title: "Interface guiada CaseFlow",
    status: "delivered",
    summary: "Resumo progressivo, evidencias, passo atual, opcoes e mensagens no side panel e Web.",
    delivered: ["Intake e stepper", "Escolhas clicaveis e caminho progressivo no piloto", "Conflitos, pendencias e intervencao humana explicitos"],
    finalVision: "Experiencia diaria validada com atendentes, teclado, zoom e dispositivos do alvo.",
    todos: ["Teste assistido com operadores", "Validar leitor de tela, zoom e monitores reais"],
    intentionalReason: "Usabilidade humana e perifericos nao podem ser inferidos apenas por automacao.",
    href: "http://localhost:5173"
  },
  {
    id: "caseflow-admin",
    group: "CaseFlow",
    title: "Administracao e saude CaseFlow",
    status: "delivered",
    summary: "Historico, regras, conectores, metricas, diagnostico, export, backup e restore de configuracao.",
    delivered: ["Painel de conectores", "Historico redigido de casos", "Backup/restore com validacao"],
    finalVision: "Operacao com alertas, owners, runbooks e evidencias live por conector.",
    todos: ["Configurar alertas no stack alvo", "Executar drills com owners e UTC registrado"],
    intentionalReason: "O painel mostra sinais locais; nao simula saude live inexistente.",
    href: "http://localhost:5173"
  },
  {
    id: "chromium-extension",
    group: "Companion",
    title: "Extensao Chromium MV3",
    status: "partial",
    summary: "Side panel, service worker, pairing, reconexao, intake e conectores controlados.",
    delivered: ["Build MV3 validado", "Side panel responsivo", "Action firewall e testes unpacked locais"],
    finalVision: "Extensao instalada no perfil corporativo com wiring completo e compatibilidade homologada.",
    todos: ["Declarar e validar content script no manifest", "Provar TabRegistry e restart reais", "Homologar Chrome/Edge no host alvo"],
    intentionalReason: "O wiring que toca a sessao diaria foi mantido fora do rollout ate existir validacao live.",
    href: "/files/apps/companion-extension/coverage/index.html"
  },
  {
    id: "companion-host",
    group: "Companion",
    title: "Companion Host local",
    status: "partial",
    summary: "Processo local para pairing, protocolo, cache, concorrencia, timeouts e resultados progressivos.",
    delivered: ["Bind e protocolo local", "Rotacao, reconexao e health", "Cache efemero e degradacao isolada"],
    finalVision: "Host empacotado, instalado e recuperavel em Windows/WSL com firewall aprovado.",
    todos: ["Ensaio Windows/WSL", "Validar firewall, VPN e suspend/resume", "Executar instalacao e rollback no alvo"],
    intentionalReason: "O rollout local exige acesso ao host e politicas corporativas que nao devem ser presumidas.",
    href: "/files/services/companion-host/coverage/index.html"
  },
  {
    id: "connectors",
    group: "Companion",
    title: "Conectores externos CaseFlow",
    status: "partial",
    summary: "Adaptadores isolados para Rastreio, Loggi, Correios Reversa, Yampi, OMIE, JT/VIP, Lancador e AlwaysChat.",
    delivered: ["Contratos, fixtures e parsers", "Timeout, drift e degradacao", "Harness e action firewall"],
    finalVision: "Cada conector homologado individualmente em sandbox/live, com owner e smoke manual.",
    todos: ["Executar smoke autorizado por sistema", "Registrar versao de pagina e evidencias redigidas", "Calibrar seletores no ambiente alvo"],
    intentionalReason: "Nenhuma credencial ou scraping real foi usado; fixtures nao contam como integracao live.",
    href: "http://localhost:5173"
  },
  {
    id: "smartscript",
    group: "Companion",
    title: "SmartScript Companion",
    status: "partial",
    summary: "Captura local controlada, processamento, importacao e exportacao opcional para Espanso.",
    delivered: ["CLI e storage isolados", "Retencao e idempotencia", "Export sem fatos CaseFlow"],
    finalVision: "Uso homologado no desktop alvo, com clipboard e Espanso sob politica explicita.",
    todos: ["Validar Espanso e clipboard reais", "Testar janela e filesystem no Windows"],
    intentionalReason: "Integracao automatica em campos desconhecidos permanece desabilitada por desenho.",
    href: "/files/apps/smartscript-companion/coverage/index.html"
  },
  {
    id: "attachments-storage",
    group: "Plataforma",
    title: "Documentos, anexos e storage",
    status: "partial",
    summary: "Uploads privados, validacao por bytes, anexos operacionais e adapter S3-compatible.",
    delivered: ["Allowlist de tipos e limites", "Storage local privado", "Arquivamento e auditoria"],
    finalVision: "Storage externo com backup, retencao, malware scan e restore ensaiado.",
    todos: ["Validar S3 no ambiente alvo", "Definir malware scanning", "Exercitar restore coordenado"],
    intentionalReason: "Storage externo depende de infraestrutura e secrets ainda nao autorizados.",
    href: "http://localhost:5173"
  },
  {
    id: "external-integrations",
    group: "Integracoes",
    title: "Google, WhatsApp e provedores de IA",
    status: "planned",
    summary: "Contratos, timeouts, redacao e degradacao existem; promocao sandbox/live permanece pendente.",
    delivered: ["Matriz de providers", "Timeout e erros normalizados", "Providers fake para caminhos deterministas"],
    finalVision: "Integracoes autorizadas individualmente, com secrets, quotas, consentimento e fallback exercitados.",
    todos: ["Obter credenciais sandbox", "Executar gates live por provider", "Aprovar tratamento de dados"],
    intentionalReason: "A demo nao usa credenciais nem envia dados a terceiros.",
    href: "/view?path=docs/security/external-integrations-security-review.md"
  },
  {
    id: "api-contracts",
    group: "Plataforma",
    title: "API, contratos e arquitetura",
    status: "delivered",
    summary: "API versionada, lifecycle, readiness, OpenAPI P0 e contratos compartilhados.",
    delivered: ["Health live/ready", "Shutdown gracioso", "OpenAPI e testes HTTP", "Fronteiras arquiteturais CaseFlow"],
    finalVision: "Cobertura OpenAPI integral e compatibilidade versionada para todos os consumidores.",
    todos: ["Documentar rotas P1/P2 restantes", "Validar compatibilidade no pipeline de release"],
    intentionalReason: "A prioridade de contrato foi dada aos fluxos P0 da demonstracao e do CaseFlow.",
    href: "/files/docs/generated/typedoc/index.html"
  },
  {
    id: "audit-security-privacy",
    group: "Governanca",
    title: "Auditoria, seguranca e privacidade",
    status: "partial",
    summary: "Audit log, redacao, action firewall, controles tenant-scoped, SAST/SCA e lifecycle de dados.",
    delivered: ["Auditoria transversal", "Firewall de acoes proibidas", "Retencao, purge e direitos locais", "Threat model e gates"],
    finalVision: "Controles aprovados por Security, Privacy e Legal no release candidato.",
    todos: ["Aprovacao juridica/RIPD", "Exercicio production-like", "Reexecutar gate de exposicao"],
    intentionalReason: "Implementacao tecnica local nao substitui aprovacao legal ou de seguranca.",
    href: "/view?path=docs/security/external-exposure-release-gate.md"
  },
  {
    id: "quality-evidence",
    group: "Qualidade",
    title: "Testes, coverage e evidencias",
    status: "delivered",
    summary: "Gates uniformes, 1.063 testes nos seis workspaces, 34 E2E aprovados, regressao visual e coverage por risco.",
    delivered: ["Lint, typecheck, testes e build", "Matriz de papeis e viewports", "Scorecard sem media enganosa", "Documentacao com integridade executavel"],
    finalVision: "Mesmos gates verdes no CI e no release candidate production-like.",
    todos: ["Observar gate Docker/CI final", "Ampliar coverage Web e SmartScript com risco", "Executar acessibilidade manual"],
    intentionalReason: "Coverage local mede execucao do codigo, nao prontidao produtiva nem qualidade isoladamente.",
    href: "/files/docs/generated/coverage/index.html"
  },
  {
    id: "performance-observability",
    group: "Operacao tecnica",
    title: "Performance e observabilidade",
    status: "partial",
    summary: "Metricas HTTP, SLOs, alertas e perfis de carga mixed, stress, spike e soak.",
    delivered: ["Instrumentacao e correlacao local", "Relatorio Artillery navegavel", "Backpressure e degradacao testaveis"],
    finalVision: "Carga e alertas exercitados com recursos, Redis e topologia equivalentes ao alvo.",
    todos: ["Rodar perfis pesados production-like", "Calibrar SLOs", "Exercitar alertas com plantao"],
    intentionalReason: "O smoke local de um VU nao e apresentado como prova de capacidade.",
    href: "/view?path=docs/performance/README.md"
  },
  {
    id: "data-recovery-release",
    group: "Operacao tecnica",
    title: "Dados, recovery e release",
    status: "planned",
    summary: "SQLite suporta a demo; adapters, runbooks, containers e drills locais preparam a evolucao.",
    delivered: ["Reset/seed seguro", "Runbooks de backup e rollback", "Container nao-root e pacote de evidencia local"],
    finalVision: "Postgres, Redis, storage, backup/PITR e rollback provados no ambiente production-like.",
    todos: ["Provisionar infraestrutura alvo", "Executar migration e restore", "Observar pipeline e provenance finais"],
    intentionalReason: "Infraestrutura externa e uma dependencia consciente; SQLite local nao foi disfarçado de producao.",
    href: "/view?path=docs/operations/backup-restore-runbook.md"
  },
  {
    id: "future-agent",
    group: "Evolucao",
    title: "Preparacao para agente futuro",
    status: "planned",
    summary: "Contratos de caso, fatos, plano, capabilities e gates ja limitam uma futura camada agentica.",
    delivered: ["Contexto estruturado e auditavel", "Ferramentas permitidas por capability", "Proibicoes de navegador, Slack e submit"],
    finalVision: "Agente opcional, avaliado e restrito, sem poder livre ou dependencia no caminho principal.",
    todos: ["Definir avaliacao e threat model especificos", "Somente iniciar depois dos gates de rollout"],
    intentionalReason: "O agente nao foi implementado nesta fase por decisao explicita da SPEC.",
    href: "/view?path=docs/architecture/caseflow-architecture.md"
  }
];

export const statusLabels = {
  delivered: "Entregue localmente",
  partial: "Parcial / gate externo",
  planned: "Planejado intencional"
};
